[package]
name = "utrace-parser-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
utrace-parser = { path = "..", features = ["utrace"] }

[[bin]]
name = "utrace_packets"
path = "fuzz_targets/utrace_packets.rs"
test = false
doc = false
bench = false
